@echo off
echo Checking if port 5000 is in use...
for /f "tokens=5" %%a in ('netstat -ano ^| findstr :5000') do (
    echo Killing process with PID %%a using port 5000...
    taskkill /F /PID %%a
)
echo Starting server...
npm run dev
